title: VWSCC-xTB
description: xTB workshop for the Virtual Winter School on Computational Chemistry 2025
theme: just-the-docs

baseurl: ""
url: https://vwscc-xtb.github.io

logo: /assets/images/xtb.svg
favicon_ico: /assets/images/xtb.svg
repository: vwscc-xtb/vwscc-xtb.github.io
color_scheme: light

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
, "docs/tests/"
]

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  focus_shortcut_key: 'k'


# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "xtb on GitHub":
    - "//github.com/grimme-lab/xtb"
  "xtb Documentation":
    - "//xtb-docs.readthedocs.io/en/latest/"

nav_sort: case_sensitive # Capital letters sorted before lowercase

# Back to top link
back_to_top: true
back_to_top_text: "Back to top <i class='fa-solid fa-circle-up'></i>"

footer_content: >
  Copyright &copy; 2025 grimme-lab.
  <br><br>
  xtb is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Lesser General Public License for more details.

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link



# callouts_level: loud
# callouts:
#   highlight:
#     color: yellow
#   important:
#     title: Important
#     color: blue
#   new:
#     title: New
#     color: green
#   note:
#     title: Note
#     color: purple
#   warning:
#     title: Warning
#     color: red


# Markdown processing
highlighter: rouge

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 syntax_highlighter_opts:
   block:
     line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-glossary_tooltip

just_the_docs:
  enable_copy_code_button: true

